# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: 'devel' }
          - { os: ubuntu-latest, r: 'release' }
          - { os: macOS-latest, r: 'release' }
          - { os: windows-latest, r: 'release' }
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R (latest version)
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'latest'
        
    # Install system dependencies required for R packages
    - name: Install system dependencies (Linux)
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y || true
        sudo apt-get install -y pandoc pandoc-citeproc

    - name: Install system dependencies (macOS)
      if: matrix.config.os == 'macOS-latest'
      run: |
        brew install pandoc

    - name: Install R dependencies
      run: |
        Rscript -e "if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"

    - name:  Run R tests
      run: 
        Rscript -e "testthat::test_file('tests/testthat/test-counts.R')"
        Rscript -e "testthat::test_file('tests/testthat/test-reordering.R')"


    - name: Check the package
      run: |
          R CMD build .
     
